--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/Phqzing/PHqx
build-by-default: true
branches:
- master
projects:
  PHqx:
    libs:
      - src: dktapps-pm-pl/pmforms/pmforms
        version: ^2.0.0
      - src: poggit/libasynql/libasynql
        version: ^4.1.0
...