---
# the plugin won't work on worlds that are listed here
# you can add as many worlds as you wan't but make sure you are getting the folder name of the world
black-listed-worlds:
  - "exampleWorld1"
  - "exampleWorld2"
  - "exampleWorld3"


# this is how often the Kill Aura checks for players nearby
# Note: value must always be positive
# 20 = 1 second
killaura-tickrate: 10


# DO NOT TOUCH UNLESS YOU KNOW EXACTLY WHAT YOU'RE DOING
database:
  type: sqlite
  sqlite:
    file: settings.sql
  worker-limit: 1
...